language: bash
services: docker
before_install:
  - cd 17\ RestWithSpringBootUdemy\ Docker/
  - echo "We are in the Docker folder!"
script:
  - docker-compose build
before_deploy:
  - echo docker | docker login --username root --password-stdin
deploy:
  provider: script
  script:
    docker push mapefi/mysql-rest-with-spring-boot-udemy;
    docker push mapefi/rest-with-spring-boot-udemy;
  on:
    branch: master
notifications:
  email: false
  
